#include "unity.h"
#include "hidra_protocol.h"

void test_protocol_constants(void)
{
    // Test HID register addresses
    TEST_ASSERT_EQUAL_HEX8(0x16, HIDRA_REG_KEYBOARD);
    TEST_ASSERT_EQUAL_HEX8(0x12, HIDRA_REG_MOUSE);
    TEST_ASSERT_EQUAL_HEX8(0x15, HIDRA_REG_GAMEPAD);
    TEST_ASSERT_EQUAL_HEX8(0xC1, HIDRA_REG_CONSUMER);
    
    // Test config register addresses
    TEST_ASSERT_EQUAL_HEX8(0xF0, CONFIG_USB_IDS_REG);
    TEST_ASSERT_EQUAL_HEX8(0xF4, CONFIG_COMPOSITE_DEVICE_REG);
    TEST_ASSERT_EQUAL_HEX8(0xFE, CONFIG_I2C_ADDR_REG);
    TEST_ASSERT_EQUAL_HEX8(0xFF, STATUS_REG);
    
    // Test status bits
    TEST_ASSERT_EQUAL_HEX8(0x01, STATUS_OK);
    TEST_ASSERT_EQUAL_HEX8(0x02, ERROR_UNKNOWN_REGISTER);
    TEST_ASSERT_EQUAL_HEX8(0x04, ERROR_PAYLOAD_TOO_LARGE);
    TEST_ASSERT_EQUAL_HEX8(0x08, ERROR_INTERFACE_DISABLED);
    TEST_ASSERT_EQUAL_HEX8(0x10, ERROR_NVS_WRITE_FAILED);
    
    // Test default values
    TEST_ASSERT_EQUAL_HEX8(0x70, DEFAULT_I2C_ADDR);
    TEST_ASSERT_EQUAL_HEX16(0x413D, DEFAULT_USB_VID);
    TEST_ASSERT_EQUAL_HEX16(0x0001, DEFAULT_USB_PID);
    TEST_ASSERT_EQUAL_HEX16(0x000B, DEFAULT_COMPOSITE_LAYOUT);
    
    // Test layout bitmap
    TEST_ASSERT_EQUAL_HEX16(0x01, LAYOUT_KEYBOARD);
    TEST_ASSERT_EQUAL_HEX16(0x02, LAYOUT_MOUSE);
    TEST_ASSERT_EQUAL_HEX16(0x08, LAYOUT_GAMEPAD);
    
    // Test combined layout
    uint16_t expected_default = LAYOUT_KEYBOARD | LAYOUT_MOUSE | LAYOUT_GAMEPAD;
    TEST_ASSERT_EQUAL_HEX16(expected_default, DEFAULT_COMPOSITE_LAYOUT);
}
